import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

import type { ServerConfig } from "../config.js";

export interface ExportStorageCapabilities {
  available: boolean;
  formats: Array<"csv" | "json" | "xlsx" | "pdf">;
  retentionHours: number;
  unavailableReason?: string;
}

export interface ExportArtifactAccess {
  capabilities(): ExportStorageCapabilities;
  createDownloadUrl(
    objectKey: string,
    fileName: string,
    contentType: string,
  ): Promise<{ url: string; expiresInSeconds: number }>;
}

/**
 * Export artifacts live in the same private S3-compatible bucket as evidence,
 * but they are generated by the Worker rather than uploaded by a browser. The
 * API only mints a short-lived GET capability after re-checking the requester.
 */
export class ExportArtifactStore implements ExportArtifactAccess {
  private readonly client: S3Client | null;
  private readonly unavailableReason: string | null;

  constructor(private readonly config: ServerConfig) {
    const complete = Boolean(
      config.S3_BUCKET && config.S3_ACCESS_KEY_ID && config.S3_SECRET_ACCESS_KEY,
    );
    this.unavailableReason = complete
      ? null
      : "私有对象存储尚未完整配置，暂时不能生成可下载的后台导出文件。";
    this.client = complete
      ? new S3Client({
          region: config.S3_REGION,
          ...(config.S3_ENDPOINT ? { endpoint: config.S3_ENDPOINT } : {}),
          forcePathStyle: config.S3_FORCE_PATH_STYLE,
          credentials: {
            accessKeyId: config.S3_ACCESS_KEY_ID!,
            secretAccessKey: config.S3_SECRET_ACCESS_KEY!,
          },
        })
      : null;
  }

  capabilities(): ExportStorageCapabilities {
    return {
      available: Boolean(this.client),
      formats: ["csv", "json", "xlsx", "pdf"],
      retentionHours: 24,
      ...(this.unavailableReason
        ? { unavailableReason: this.unavailableReason }
        : {}),
    };
  }

  async createDownloadUrl(
    objectKey: string,
    fileName: string,
    contentType: string,
  ): Promise<{ url: string; expiresInSeconds: number }> {
    if (!this.client || !this.config.S3_BUCKET) {
      throw new Error(this.unavailableReason ?? "后台导出对象存储不可用。");
    }
    const expiresInSeconds = Math.min(this.config.SIGNED_URL_TTL_SECONDS, 300);
    // Keep the signed response headers ASCII-only. The original localized
    // filename remains in authenticated job metadata and the UI download
    // attribute; this fallback is safe across S3-compatible providers.
    const fallbackName = fileName
      .normalize("NFKC")
      .replace(/[^A-Za-z0-9._-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "workbench-export";
    const command = new GetObjectCommand({
      Bucket: this.config.S3_BUCKET,
      Key: objectKey,
      ResponseContentDisposition: `attachment; filename="${fallbackName}"`,
      ResponseContentType: contentType,
      ResponseCacheControl: "private, no-store",
    });
    return {
      url: await getSignedUrl(this.client, command, { expiresIn: expiresInSeconds }),
      expiresInSeconds,
    };
  }
}
